# Generated by Django 5.2.2 on 2025-06-25 04:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_introduction', models.TextField(blank=True, help_text='Course introduction', max_length=500, null=True)),
                ('course_overview', models.TextField(blank=True, help_text='Course overview', max_length=500, null=True)),
                ('course_requirements', models.TextField(blank=True, help_text='Course requirements', max_length=500, null=True)),
                ('course_context', models.TextField(blank=True, help_text='Course context', max_length=500, null=True)),
            ],
        ),
    ]
