# Generated by Django 5.2.3 on 2025-06-28 12:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.TextField(blank=True, help_text='Residential address of the user.', null=True, verbose_name='Address')),
                ('phone_no', models.CharField(blank=True, help_text='Contact phone number. Include country code (e.g. +997-9812345678).', max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?[0-9\\-]{10,15}$')], verbose_name='Phone Number')),
                ('profile_picture', models.ImageField(blank=True, help_text='Optional profile picture uploaded by the user.', null=True, upload_to='profile_pictures/', verbose_name='Profile Picture')),
                ('is_approved', models.BooleanField(default=False, help_text='Indicates whether the student has been approved to enroll in the course.', verbose_name='Is Approved')),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('student', 'Student')], db_index=True, default='student', help_text='Primary role determining user permissions and access level.', max_length=20, verbose_name='User Role'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_user_role_36d76d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_user_is_acti_ddda02_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined'], name='users_user_date_jo_064c8f_idx'),
        ),
    ]
