# Generated by Django 5.2.3 on 2025-06-22 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text="User's unique email address.", max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(blank=True, help_text='Contact phone number. Include country code (e.g. +997-9812345678).', max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?[0-9\\-]{10,15}$')], verbose_name='Phone Number'),
        ),
    ]
