# Generated by Django 5.2.3 on 2025-06-30 10:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Numeric rating between 0.0 and 5.0 (required)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0, message='Rating cannot be less than 0'), django.core.validators.MaxValueValidator(5.0, message='Rating cannot exceed 5')])),
                ('review', models.TextField(blank=True, help_text='Optional detailed review text (max 2000 chars)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Automatic timestamp when rating was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatic timestamp when rating was last updated')),
                ('course', models.ForeignKey(help_text='The course being rated (required)', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='courses.course')),
                ('user', models.ForeignKey(help_text='User who submitted the rating (required)', on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Rating',
                'verbose_name_plural': 'Course Ratings',
                'ordering': ['-created_at'],
                'unique_together': {('course', 'user')},
            },
        ),
    ]
