# Generated by Django 5.2.2 on 2025-07-04 14:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Numeric rating between 0.0 and 5.0 (required)', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), message='Rating cannot be less than 0'), django.core.validators.MaxValueValidator(Decimal('5.00'), message='Rating cannot exceed 5')])),
                ('review', models.TextField(blank=True, help_text='Optional detailed review text (max 2000 chars)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Automatic timestamp when rating was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatic timestamp when rating was last updated')),
            ],
            options={
                'verbose_name': 'Course Rating',
                'verbose_name_plural': 'Course Ratings',
                'ordering': ['-created_at'],
            },
        ),
    ]
