# Generated by Django 5.2.2 on 2025-07-06 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_ratings', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserating',
            name='course',
            field=models.ForeignKey(help_text='The course being rated (required)', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='courses.course'),
        ),
    ]
