# Generated by Django 5.2.2 on 2025-06-25 04:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSyllabus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('syllabus_title_indexing', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'CourseSyllabus',
                'verbose_name_plural': 'CourseSyllabus',
                'indexes': [models.Index(fields=['title'], name='course_syll_title_3d10f5_idx'), models.Index(fields=['syllabus_title_indexing'], name='course_syll_syllabu_b00fdc_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourseSyllabusTitleContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title_content', models.CharField(blank=True, max_length=255, null=True)),
                ('syllabus_title_content_indexing', models.PositiveIntegerField(unique=True)),
                ('syllabus_title_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_syllabus.coursesyllabus')),
            ],
            options={
                'verbose_name': 'CourseSyllabusTitleContent',
                'verbose_name_plural': 'CourseSyllabusTitleContents',
                'indexes': [models.Index(fields=['title_content'], name='course_syll_title_c_c3088c_idx'), models.Index(fields=['syllabus_title_content_indexing'], name='course_syll_syllabu_ce3246_idx')],
            },
        ),
    ]
