# Generated by Django 5.2.3 on 2025-06-30 10:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the course', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Short name of the course (e.g., Python Basics)', max_length=100, unique=True)),
                ('title', models.CharField(help_text='Full title or description of the course', max_length=500)),
                ('duration_weeks', models.PositiveIntegerField(default=4, help_text='Course duration in weeks', validators=[django.core.validators.MinValueValidator(1, message='Duration must be at least 1 week')])),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Course price in NPR', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0, message='Price cannot be negative')])),
                ('training_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text='Skill level required to take this course', max_length=100)),
                ('class_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], default='online', help_text='Type of class delivery', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Course promotional image', null=True, upload_to='courses/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when course was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when course was last updated')),
                ('overview', models.TextField(blank=True, help_text='Detailed course overview and introduction', null=True)),
                ('objectives', models.TextField(blank=True, help_text='Learning objectives (one per line)')),
                ('prerequisites', models.TextField(blank=True, help_text='Required knowledge before taking this course (one per line)')),
                ('outcomes', models.TextField(blank=True, help_text='What students will achieve (one per line)')),
                ('curriculum', models.JSONField(blank=True, default=list, help_text='Weekly curriculum structure')),
                ('categories', models.ManyToManyField(help_text='Categories this course belongs to', related_name='category', to='category.category')),
                ('owner', models.ForeignKey(blank=True, help_text='User who created this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['duration_weeks', 'price', '-created_at', 'training_level'],
                'indexes': [models.Index(fields=['name'], name='courses_cou_name_eb4cc3_idx'), models.Index(fields=['duration_weeks'], name='courses_cou_duratio_880223_idx'), models.Index(fields=['price'], name='courses_cou_price_1fbd18_idx'), models.Index(fields=['training_level'], name='courses_cou_trainin_4e50b2_idx')],
            },
        ),
    ]
