# Generated by Django 5.2.3 on 2025-06-22 05:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Short name of the course (e.g., Python Basics)', max_length=100, unique=True)),
                ('title', models.CharField(help_text='Full title or description of the course', max_length=500)),
                ('duration', models.DurationField(help_text='Expected course duration (e.g., 1 week, 30 days)')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Course price in NPR', max_digits=10)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average course rating from 0.0 to 5.0', max_digits=3)),
                ('training_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text='Skill level required to take this course', max_length=100)),
                ('class_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], default='online', help_text='Type of class delivery', max_length=100)),
                ('career_prospect', models.CharField(help_text='Main career outcomes this course prepares for', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Course promotional image', null=True, upload_to='courses/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['duration', '-rating', 'price', '-created_at', 'training_level'],
                'indexes': [models.Index(fields=['name'], name='courses_cou_name_eb4cc3_idx'), models.Index(fields=['duration'], name='courses_cou_duratio_972589_idx'), models.Index(fields=['rating'], name='courses_cou_rating_b9c925_idx'), models.Index(fields=['price'], name='courses_cou_price_1fbd18_idx'), models.Index(fields=['training_level'], name='courses_cou_trainin_4e50b2_idx')],
            },
        ),
    ]
