# Generated by Django 5.2.2 on 2025-07-06 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who created this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['name'], name='courses_cou_name_eb4cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['duration_weeks'], name='courses_cou_duratio_880223_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['price'], name='courses_cou_price_1fbd18_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['training_level'], name='courses_cou_trainin_4e50b2_idx'),
        ),
    ]
