# Generated by Django 5.2.3 on 2025-07-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='Cached average of all ratings (auto-updated)', max_digits=3),
        ),
    ]
