# Generated by Django 5.2.2 on 2025-07-06 16:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the enrollment record', primary_key=True, serialize=False)),
                ('approved_by', models.CharField(blank=True, choices=[('admin', 'Admin'), ('moderator', 'Moderator')], help_text='Role of the person who approved this enrollment', null=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('denied', 'Denied'), ('pending', 'Pending')], default='pending', help_text='Current status of the enrollment request')),
                ('payment', models.CharField(choices=[('paid', 'Paid'), ('Not paid', 'not paid'), ('Pending', 'Pending')], default='unpaid', help_text='Current status of the payment request')),
                ('applied_Date', models.DateTimeField(auto_now_add=True, help_text='Date when the enrollment was first applied for')),
                ('Enrolled_Date', models.DateTimeField(blank=True, help_text='Date when the enrollment was officially processed', null=True)),
                ('whatsApp', models.CharField(help_text='WhatsApp app number of a enroll person')),
                ('refer_by', models.CharField(blank=True, help_text='WhatsApp app number of a person who refer to the enrollment', null=True)),
                ('fullName', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('course', models.ForeignKey(help_text='The course being enrolled in', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-applied_Date'],
            },
        ),
    ]
