# Generated by Django 5.2.2 on 2025-07-01 04:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('enrollment', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-applied_Date'], 'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Enrolled_Date',
            field=models.DateTimeField(blank=True, help_text='Date when the enrollment was officially processed', null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='applied_Date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date when the enrollment was first applied for'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='approved_by',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('moderator', 'Moderator')], help_text='Role of the person who approved this enrollment', null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(help_text='The course being enrolled in', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the enrollment record', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('denied', 'Denied'), ('pending', 'Pending')], default='pending', help_text='Current status of the enrollment request'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(help_text='The user requesting enrollment', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
    ]
